# This file provides instructions for packaging.

`Module-Hash`
	perl_version_from m`Module::Hash`;
	version_from      m`Module::Hash`;
	readme_from       m`Module::Hash`;
	test_requires     p`Test::More 0.61`;
	requires          p`Module::Runtime 0.002`;
.

